apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-python
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/demotto/hallo-python:1.0.0
        env:
        - name: TARGET
          value: "Python Sample v1"